FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1000 runner && \
    useradd --uid 1000 --home-dir /data --create-home --gid runner runner

USER runner

VOLUME /data
WORKDIR /data

EXPOSE 8080/tcp
COPY lowestbins ./
CMD ["./lowestbins"]