name: Build and upload artifacts.

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg reqwest_unstable"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - name: Cargo Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --release
      - run: cp target/release/lowestbins .
      - name: Build and push
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          registry: ghcr.io
          image: "lowestbins"
          dockerfile: Dockerfile.prebuild
          tags: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: lowestbins
          path: ./lowestbins
          if-no-files-found: error
